#Start
os: linux
arch: ppc64le
dist: bionic
language: go
go: 1.14.x
cache:
- npm
- yarn

install:
  - sudo apt update
  - sudo apt install -y lftp
  - alias python=/usr/local/bin/python3
  - python3 ftp_version.py
  - wget --quiet https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs
  - sudo chmod 777 phantomjs
  - sudo mv phantomjs /bin
  - nvm install 12.13.1
  - npm install -g yarn

script:
  - bash build.sh
  - bash release.sh
